---
title: "HW2"
author: "Yiquan Zhou"
date: "2025-10-01"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Package
library(tidyverse)
library(janitor)
library(readxl)
```

## Problem 1
```{r}
#Load Dataset
month.data <- read_csv(file = "./fivethirtyeight_datasets/pols-month.csv")
unemp.data <- read_csv(file = "./fivethirtyeight_datasets/unemployment.csv")
snp.data <- read_csv(file = "./fivethirtyeight_datasets/snp.csv")
```
```{r}
#Clean Month name
month.data <- janitor::clean_names(month.data)

#Clean Month data
month.data <- month.data %>%
  separate(mon, into = c("year", "month","day"), sep = "-") %>% #separate date column into year month day
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = month.name[month], #turn to month name
    president = if_else(prez_gop == 1, "gop", "dem") #president variable showing dem or gop
    )

#Select columns and remove gop prez and day 
month.data <- select(month.data, -prez_dem, -prez_gop, -day)
```

```{r}
#Clean snp name
snp.data <- janitor::clean_names(snp.data)

#Clean Month data
snp.data <- snp.data %>%
  mutate(date = mdy(date)) %>% #standard the date format first
  separate(date, into = c("year", "month","day"), sep = "-") %>% #separate date column into year month day
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = month.name[month] #turn to month name
  )

#Remove day 
snp.data <- select(snp.data, -day)
```

```{r}
#Clean unemployment name
unemp.data <- janitor::clean_names(unemp.data)

#pivot longer to change the data form
unemp.data = 
  pivot_longer(
    unemp.data, 
    jan:dec,
    names_to = "month", 
    values_to = "unemployment")

#integar year and also reformat month name
unemp.data <- unemp.data %>%
  mutate(
    year = as.integer(year),
    month_fac = factor(month, levels = tolower(month.abb), ordered = TRUE), 
    #Since the month is abbreviation
    #month.name would return NA, factor the month turn into numbers and then use month.name
    month_num = as.integer(month_fac),
    month = month.name[month_num]
  )

#select columns
unemp.data <- unemp.data %>%
  select(year, month, unemployment)
```

```{r}
#merge datasets
final_data_1 <- month.data %>%
  left_join(snp.data, by = c("year","month")) %>%
  left_join(unemp.data, by = c("year","month"))
```

## Problem 2
```{r}
#load the Mr Trash wheel sheet with the correct range
trash.data <- read_excel("./202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N653")
```

```{r}
#Clean snp name
trash.data <- janitor::clean_names(trash.data)

#Clean Trash data
trash.data <- trash.data%>%
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr_Trash_Wheel"
  )
```

```{r}
#load the Professor Trash Wheel sheet with the correct range
prof.data <- read_excel("./202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1)
```

